### PR TITLE
Add QSVC, PegasosQSVC, and fix errors in QuantumKernel Benchmarks

### PR DESCRIPTION
**Pull request by Abrar2652**
### Summary

We added QSVC and PegasosQSVC benchmarks based on the QuantumKernel. Additionally, fixed some errors and typos in QuantumKernel and QuantumKernelTrainer benchmarks.

### CODE REVIEW

**Comment by Abrar2652** [comment]
@Gruntrexpewrus Hi, let's try this PR again to check whether we need more time to fix the errors or not.

**Comment by Gruntrexpewrus** [comment]
I appreciate your work and I am discussing if we should add it anyway, but why are you working on a pr without asking first?

**Comment by Abrar2652** [comment]
> I appreciate your work and I am discussing if we should add it anyway, but why are you working on a pr without asking first?

@Gruntrexpewrus Thanks. This is my first-time open source contribution on GitHub. I didn't know about the PR ethics. Sincere apologies.

**Comment by Abrar2652** [comment]
> I appreciate your work and I am discussing if we should add it anyway, but why are you working on a pr without asking first?

@Gruntrexpewrus Thanks. This is my first-time open source contribution on GitHub. I didn't know about the PR ethics. Sincere apologies.

**Comment by Abrar2652** [comment]
@Gruntrexpewrus I think I explained to you that my first time open source contribution went
wrong. It's really demeaning attempt when you publicly down someone in
front of others. As soon as I got to learn about the rule, I closed my PR.
I would be glad if you would delete that demeaning remark.

**Comment by Gruntrexpewrus** [comment]
I am sorry, but that is the truth and I will leave it. 
I do not mean to offend you or demean you, also I checked and this is not the first time you tried contributions, also you have a clear GitHub page, so you are not a complete novice. I understand you want to become Qiskit Advocate, I have no problems with you. I am very calm about this story and understand you, I just need to set straight that you do not take other people's work without even asking and pass it as completely yours. Furthermore, I am sure this does not affect you negatively, we understand you are eager to contribute, and we will soon discuss if we should accept it without any hard feeling.

**Pull request closed without merging**
